a = int(input())
b = int(input())

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)
print("a // b = ", a // b)
print("a ** b = ", a ** b)
print("a > b : ", a > b)
print("a < b : ", a < b)
print("a bằng b : ", a == b)
print("a And b", a & b)
print("a xor b", a ^ b)
print("a or b", a | b)
print("not a == b", not a == b )
print("a dịch phải 5 bit", a >> 5)
print("a dịch trái 6 bit", a << 6)
